name: PBRP Build Silver Fox

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cleanup & Prepare Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev-i386 lib32ncurses-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc bison build-essential curl flex g++-multilib gcc-multilib gettext git gnupg gperf lib32ncurses-dev lib32z1-dev liblz4-tool libncurses-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3

      - name: Install Repo Tool
        run: |
          sudo apt-get update
          sudo apt-get install repo -y

      - name: Initialize PBRP Manifest
        run: |
          # 0. Качаем repo из проверенного репозитория Akhil Narang
          curl https://raw.githubusercontent.com/akhilnarang/scripts/master/repo > repo
          chmod a+x repo
          export PATH=$PWD:$PATH # Добавляем локальный repo в путь

          # 1. Настраиваем Git максимально жестко, чтобы не было вопросов и создаем рабочую папку
          mkdir -p work # Создаем рабочую папку...
          git config --global user.name "SilverFox"
          git config --global user.email "silver@fox.com"
          git config --global color.ui false
          echo "Configuring GIT for futher processing..."
          echo "Make working folder..."
          cd work # ...заходим в рабочую папку!
          echo "Change location to working folder..."
          
          # 2. Инициализация (создает папку .repo внутри work). На все запросы ОС автоматически дается ответ "yes".
          echo "Starting repo init..."
          yes | ../repo init --no-clone-bundle --depth=1 -u https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-12.1

          # 3. Теперь, когда .repo существует, закидываем туда костыли
          echo "Applying fixes..."
          mkdir -p .repo/manifests
          touch .repo/remove-minimal.xml
          touch .repo/manifests/remove-minimal.xml

          # 4. Локальный манифест устройства
          echo "Setting up local manifest..."
          mkdir -p .repo/local_manifests
          cp ../pbrp-default.xml .repo/local_manifests/pbrp-default.xml
          ls -R .repo/remove-minimal.xml .repo/manifests/remove-minimal.xml # На всякий случай проверяем, что они создались (увидим в логах)
          # Сообщение о завершении инициализации
          echo "Initialization complete!"
 
      - name: Repo Sync
        run: |
          cd work
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Clone Device Tree
        run: |
          cd work
          git clone ${{ github.server_url }}/${{ github.repository }} -b pbrp-12.1 device/tecno/le7n

      - name: Building PBRP
        run: |
          cd work
          . build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          lunch pb_tecno_le7n-eng
          mka pbrp -j$(nproc --all)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PBRP-SilverFox-le7n
          path: work/out/target/product/le7n/*.img
